site_name: DAF2 Documentation

nav:
    - About: about.md 
    - Progress: progress.md 
    - Camp: camp.md
    - Howto:
        - 'Generate reward links': 'howto/generateRewardLinks.md'
        - 'Manage neighbours': 'howto/manageNeighbour.md'
        - 'Enable Add Me button': 'howto/facebook/addMe.md'

theme: readthedocs
