site_name: DAF2 Documentation

nav:
    - About: stub.md
    - Progress: stub.md
    - Camp: camp.md
    - 'How to':
        - Facebook related:
            - 'Enable Add Me Button': 'howto/facebook/addMe.md'
            - 'Secure Friend List': 'howto/facebook/onlyMe.md'
        - 'Generate reward links': stub.md
        - 'Manage neighbours': stub.md

theme: readthedocs
