site_name: DAF2 Documentation

nav:
    - Home: index.md
    - About: about.md 
    - Progress: progress.md 
    - Camp: camp.md
    - Howto:
        - 'Generate reward links': howto/generateRewardLinks.md
        - 'Manage neighbours': howto/manageNeighbour.md

theme: readthedocs
